// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['main']['P2Papp']['Add'](arg1, arg2);
}

export function AddDm(arg1) {
  return window['go']['main']['P2Papp']['AddDm'](arg1);
}

export function AddRendezvous(arg1) {
  return window['go']['main']['P2Papp']['AddRendezvous'](arg1);
}

export function CancelRendezvous() {
  return window['go']['main']['P2Papp']['CancelRendezvous']();
}

export function Clear() {
  return window['go']['main']['P2Papp']['Clear']();
}

export function DataChanged() {
  return window['go']['main']['P2Papp']['DataChanged']();
}

export function DeleteChat(arg1) {
  return window['go']['main']['P2Papp']['DeleteChat'](arg1);
}

export function DeriveKey(arg1, arg2) {
  return window['go']['main']['P2Papp']['DeriveKey'](arg1, arg2);
}

export function DhtRoutine(arg1) {
  return window['go']['main']['P2Papp']['DhtRoutine'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['P2Papp']['EmitEvent'](arg1, arg2);
}

export function FakeUsers() {
  return window['go']['main']['P2Papp']['FakeUsers']();
}

export function Get(arg1) {
  return window['go']['main']['P2Papp']['Get'](arg1);
}

export function GetData() {
  return window['go']['main']['P2Papp']['GetData']();
}

export function GetKeys() {
  return window['go']['main']['P2Papp']['GetKeys']();
}

export function GetPeerIDfromstring(arg1) {
  return window['go']['main']['P2Papp']['GetPeerIDfromstring'](arg1);
}

export function GetRend() {
  return window['go']['main']['P2Papp']['GetRend']();
}

export function GetTimer(arg1) {
  return window['go']['main']['P2Papp']['GetTimer'](arg1);
}

export function InitDHT() {
  return window['go']['main']['P2Papp']['InitDHT']();
}

export function LeaveChat(arg1) {
  return window['go']['main']['P2Papp']['LeaveChat'](arg1);
}

export function ListChats() {
  return window['go']['main']['P2Papp']['ListChats']();
}

export function ListUsers() {
  return window['go']['main']['P2Papp']['ListUsers']();
}

export function MoveQueue() {
  return window['go']['main']['P2Papp']['MoveQueue']();
}

export function NewHost() {
  return window['go']['main']['P2Papp']['NewHost']();
}

export function NewID(arg1, arg2) {
  return window['go']['main']['P2Papp']['NewID'](arg1, arg2);
}

export function OpenFileExplorer(arg1) {
  return window['go']['main']['P2Papp']['OpenFileExplorer'](arg1);
}

export function OpenID(arg1, arg2) {
  return window['go']['main']['P2Papp']['OpenID'](arg1, arg2);
}

export function QueueFile(arg1, arg2) {
  return window['go']['main']['P2Papp']['QueueFile'](arg1, arg2);
}

export function ReadKeys(arg1) {
  return window['go']['main']['P2Papp']['ReadKeys'](arg1);
}

export function Reconnect(arg1) {
  return window['go']['main']['P2Papp']['Reconnect'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['P2Papp']['SelectFiles']();
}

export function SendFile(arg1, arg2) {
  return window['go']['main']['P2Papp']['SendFile'](arg1, arg2);
}

export function SendTextHandler(arg1, arg2) {
  return window['go']['main']['P2Papp']['SendTextHandler'](arg1, arg2);
}

export function SetPeers(arg1, arg2) {
  return window['go']['main']['P2Papp']['SetPeers'](arg1, arg2);
}

export function SetTimer(arg1, arg2) {
  return window['go']['main']['P2Papp']['SetTimer'](arg1, arg2);
}
